### ISSUE TITLE
Missing linter

### ISSUE THREAD

**Issue by andronat** [golangci/awesome-go-linters#4]
I found an additional interesting linter here. Could you please add it?

Link: https://github.com/mgechev/revive

**Comment by chavacava** [comment]
The line to add under Misc section could be:

`* [revive](https://github.com/mgechev/revive) - ~6x faster, stricter, configurable, extensible, and beautiful drop-in replacement for golint.`

**Comment by jirfag** [comment]
hi,
done in #5
